# SPDX-FileCopyrightText: 2021 Fred Liu <yclw3d2y@live.com>
#
# SPDX-License-Identifier: GPL-3.0-only

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: latest
    hooks:
      - id: reuse
